version: '3'
services:
  api:
    image: scrabble-score-api
    build: .
    networks:
      - backend
    ports:
      - '3000:3000'

  web-cli:
    image: scrabble-score-api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
